#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QuanLyQuayThuoc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuayThuocBenhVien")]
	public partial class QuayThuocDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    #endregion
		
		public QuayThuocDataContext() : 
				base(global::DAL_QuanLyQuayThuoc.Properties.Settings.Default.QuayThuocBenhVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuayThuocDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuayThuocDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuayThuocDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuayThuocDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _DisplayName;
		
		private string _PassWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Thuoc;
		
		private string _Ma_NCC;
		
		private string _Ten_Thuoc;
		
		private string _CongDung_Thuoc;
		
		private string _DonViTinh_Thuoc;
		
		private int _DonGia_Thuoc;
		
		private System.DateTime _NSX_Thuoc;
		
		private System.DateTime _HSD_Thuoc;
		
		private int _SoLuongThuoc;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_ThuocChanging(string value);
    partial void OnMa_ThuocChanged();
    partial void OnMa_NCCChanging(string value);
    partial void OnMa_NCCChanged();
    partial void OnTen_ThuocChanging(string value);
    partial void OnTen_ThuocChanged();
    partial void OnCongDung_ThuocChanging(string value);
    partial void OnCongDung_ThuocChanged();
    partial void OnDonViTinh_ThuocChanging(string value);
    partial void OnDonViTinh_ThuocChanged();
    partial void OnDonGia_ThuocChanging(int value);
    partial void OnDonGia_ThuocChanged();
    partial void OnNSX_ThuocChanging(System.DateTime value);
    partial void OnNSX_ThuocChanged();
    partial void OnHSD_ThuocChanging(System.DateTime value);
    partial void OnHSD_ThuocChanged();
    partial void OnSoLuongThuocChanging(int value);
    partial void OnSoLuongThuocChanged();
    #endregion
		
		public Thuoc()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Thuoc", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Thuoc
		{
			get
			{
				return this._Ma_Thuoc;
			}
			set
			{
				if ((this._Ma_Thuoc != value))
				{
					this.OnMa_ThuocChanging(value);
					this.SendPropertyChanging();
					this._Ma_Thuoc = value;
					this.SendPropertyChanged("Ma_Thuoc");
					this.OnMa_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NCC", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Ma_NCC
		{
			get
			{
				return this._Ma_NCC;
			}
			set
			{
				if ((this._Ma_NCC != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ma_NCC = value;
					this.SendPropertyChanged("Ma_NCC");
					this.OnMa_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Thuoc", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_Thuoc
		{
			get
			{
				return this._Ten_Thuoc;
			}
			set
			{
				if ((this._Ten_Thuoc != value))
				{
					this.OnTen_ThuocChanging(value);
					this.SendPropertyChanging();
					this._Ten_Thuoc = value;
					this.SendPropertyChanged("Ten_Thuoc");
					this.OnTen_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongDung_Thuoc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CongDung_Thuoc
		{
			get
			{
				return this._CongDung_Thuoc;
			}
			set
			{
				if ((this._CongDung_Thuoc != value))
				{
					this.OnCongDung_ThuocChanging(value);
					this.SendPropertyChanging();
					this._CongDung_Thuoc = value;
					this.SendPropertyChanged("CongDung_Thuoc");
					this.OnCongDung_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh_Thuoc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DonViTinh_Thuoc
		{
			get
			{
				return this._DonViTinh_Thuoc;
			}
			set
			{
				if ((this._DonViTinh_Thuoc != value))
				{
					this.OnDonViTinh_ThuocChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh_Thuoc = value;
					this.SendPropertyChanged("DonViTinh_Thuoc");
					this.OnDonViTinh_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia_Thuoc", DbType="Int NOT NULL")]
		public int DonGia_Thuoc
		{
			get
			{
				return this._DonGia_Thuoc;
			}
			set
			{
				if ((this._DonGia_Thuoc != value))
				{
					this.OnDonGia_ThuocChanging(value);
					this.SendPropertyChanging();
					this._DonGia_Thuoc = value;
					this.SendPropertyChanged("DonGia_Thuoc");
					this.OnDonGia_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSX_Thuoc", DbType="DateTime NOT NULL")]
		public System.DateTime NSX_Thuoc
		{
			get
			{
				return this._NSX_Thuoc;
			}
			set
			{
				if ((this._NSX_Thuoc != value))
				{
					this.OnNSX_ThuocChanging(value);
					this.SendPropertyChanging();
					this._NSX_Thuoc = value;
					this.SendPropertyChanged("NSX_Thuoc");
					this.OnNSX_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSD_Thuoc", DbType="DateTime NOT NULL")]
		public System.DateTime HSD_Thuoc
		{
			get
			{
				return this._HSD_Thuoc;
			}
			set
			{
				if ((this._HSD_Thuoc != value))
				{
					this.OnHSD_ThuocChanging(value);
					this.SendPropertyChanging();
					this._HSD_Thuoc = value;
					this.SendPropertyChanged("HSD_Thuoc");
					this.OnHSD_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongThuoc", DbType="Int NOT NULL")]
		public int SoLuongThuoc
		{
			get
			{
				return this._SoLuongThuoc;
			}
			set
			{
				if ((this._SoLuongThuoc != value))
				{
					this.OnSoLuongThuocChanging(value);
					this.SendPropertyChanging();
					this._SoLuongThuoc = value;
					this.SendPropertyChanged("SoLuongThuoc");
					this.OnSoLuongThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_HoaDon", Storage="_HoaDons", ThisKey="Ma_Thuoc", OtherKey="Ma_Thuoc")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Thuoc", Storage="_NhaCungCap", ThisKey="Ma_NCC", OtherKey="Ma_NCC", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._Ma_NCC = value.Ma_NCC;
					}
					else
					{
						this._Ma_NCC = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_HD;
		
		private int _Ma_KhachHang;
		
		private string _Ma_Thuoc;
		
		private System.DateTime _NgayLap_HD;
		
		private int _SoLuong_HD;
		
		private string _Loai_HD;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_HDChanging(int value);
    partial void OnMa_HDChanged();
    partial void OnMa_KhachHangChanging(int value);
    partial void OnMa_KhachHangChanged();
    partial void OnMa_ThuocChanging(string value);
    partial void OnMa_ThuocChanged();
    partial void OnNgayLap_HDChanging(System.DateTime value);
    partial void OnNgayLap_HDChanged();
    partial void OnSoLuong_HDChanging(int value);
    partial void OnSoLuong_HDChanged();
    partial void OnLoai_HDChanging(string value);
    partial void OnLoai_HDChanged();
    #endregion
		
		public HoaDon()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_HD
		{
			get
			{
				return this._Ma_HD;
			}
			set
			{
				if ((this._Ma_HD != value))
				{
					this.OnMa_HDChanging(value);
					this.SendPropertyChanging();
					this._Ma_HD = value;
					this.SendPropertyChanged("Ma_HD");
					this.OnMa_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KhachHang", DbType="Int NOT NULL")]
		public int Ma_KhachHang
		{
			get
			{
				return this._Ma_KhachHang;
			}
			set
			{
				if ((this._Ma_KhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._Ma_KhachHang = value;
					this.SendPropertyChanged("Ma_KhachHang");
					this.OnMa_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Thuoc", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Ma_Thuoc
		{
			get
			{
				return this._Ma_Thuoc;
			}
			set
			{
				if ((this._Ma_Thuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_ThuocChanging(value);
					this.SendPropertyChanging();
					this._Ma_Thuoc = value;
					this.SendPropertyChanged("Ma_Thuoc");
					this.OnMa_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap_HD", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLap_HD
		{
			get
			{
				return this._NgayLap_HD;
			}
			set
			{
				if ((this._NgayLap_HD != value))
				{
					this.OnNgayLap_HDChanging(value);
					this.SendPropertyChanging();
					this._NgayLap_HD = value;
					this.SendPropertyChanged("NgayLap_HD");
					this.OnNgayLap_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong_HD", DbType="Int NOT NULL")]
		public int SoLuong_HD
		{
			get
			{
				return this._SoLuong_HD;
			}
			set
			{
				if ((this._SoLuong_HD != value))
				{
					this.OnSoLuong_HDChanging(value);
					this.SendPropertyChanging();
					this._SoLuong_HD = value;
					this.SendPropertyChanged("SoLuong_HD");
					this.OnSoLuong_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_HD", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Loai_HD
		{
			get
			{
				return this._Loai_HD;
			}
			set
			{
				if ((this._Loai_HD != value))
				{
					this.OnLoai_HDChanging(value);
					this.SendPropertyChanging();
					this._Loai_HD = value;
					this.SendPropertyChanged("Loai_HD");
					this.OnLoai_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_HoaDon", Storage="_Thuoc", ThisKey="Ma_Thuoc", OtherKey="Ma_Thuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._Ma_Thuoc = value.Ma_Thuoc;
					}
					else
					{
						this._Ma_Thuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="Ma_KhachHang", OtherKey="Ma_KhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._Ma_KhachHang = value.Ma_KhachHang;
					}
					else
					{
						this._Ma_KhachHang = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_KhachHang;
		
		private string _Ten_KhachHang;
		
		private string _DiaChi_KhachHang;
		
		private string _Sdt_KhachHang;
		
		private string _BenhAn_KhachHang;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KhachHangChanging(int value);
    partial void OnMa_KhachHangChanged();
    partial void OnTen_KhachHangChanging(string value);
    partial void OnTen_KhachHangChanged();
    partial void OnDiaChi_KhachHangChanging(string value);
    partial void OnDiaChi_KhachHangChanged();
    partial void OnSdt_KhachHangChanging(string value);
    partial void OnSdt_KhachHangChanged();
    partial void OnBenhAn_KhachHangChanging(string value);
    partial void OnBenhAn_KhachHangChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_KhachHang
		{
			get
			{
				return this._Ma_KhachHang;
			}
			set
			{
				if ((this._Ma_KhachHang != value))
				{
					this.OnMa_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._Ma_KhachHang = value;
					this.SendPropertyChanged("Ma_KhachHang");
					this.OnMa_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_KhachHang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_KhachHang
		{
			get
			{
				return this._Ten_KhachHang;
			}
			set
			{
				if ((this._Ten_KhachHang != value))
				{
					this.OnTen_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._Ten_KhachHang = value;
					this.SendPropertyChanged("Ten_KhachHang");
					this.OnTen_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi_KhachHang", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string DiaChi_KhachHang
		{
			get
			{
				return this._DiaChi_KhachHang;
			}
			set
			{
				if ((this._DiaChi_KhachHang != value))
				{
					this.OnDiaChi_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChi_KhachHang = value;
					this.SendPropertyChanged("DiaChi_KhachHang");
					this.OnDiaChi_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt_KhachHang", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Sdt_KhachHang
		{
			get
			{
				return this._Sdt_KhachHang;
			}
			set
			{
				if ((this._Sdt_KhachHang != value))
				{
					this.OnSdt_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._Sdt_KhachHang = value;
					this.SendPropertyChanged("Sdt_KhachHang");
					this.OnSdt_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BenhAn_KhachHang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BenhAn_KhachHang
		{
			get
			{
				return this._BenhAn_KhachHang;
			}
			set
			{
				if ((this._BenhAn_KhachHang != value))
				{
					this.OnBenhAn_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._BenhAn_KhachHang = value;
					this.SendPropertyChanged("BenhAn_KhachHang");
					this.OnBenhAn_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="Ma_KhachHang", OtherKey="Ma_KhachHang")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_NCC;
		
		private string _Ten_NCC;
		
		private string _DiaChi_NCC;
		
		private string _Sdt_NCC;
		
		private string _LoaiThuoc_NCC;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_NCCChanging(string value);
    partial void OnMa_NCCChanged();
    partial void OnTen_NCCChanging(string value);
    partial void OnTen_NCCChanged();
    partial void OnDiaChi_NCCChanging(string value);
    partial void OnDiaChi_NCCChanged();
    partial void OnSdt_NCCChanging(string value);
    partial void OnSdt_NCCChanged();
    partial void OnLoaiThuoc_NCCChanging(string value);
    partial void OnLoaiThuoc_NCCChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NCC", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_NCC
		{
			get
			{
				return this._Ma_NCC;
			}
			set
			{
				if ((this._Ma_NCC != value))
				{
					this.OnMa_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ma_NCC = value;
					this.SendPropertyChanged("Ma_NCC");
					this.OnMa_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_NCC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_NCC
		{
			get
			{
				return this._Ten_NCC;
			}
			set
			{
				if ((this._Ten_NCC != value))
				{
					this.OnTen_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ten_NCC = value;
					this.SendPropertyChanged("Ten_NCC");
					this.OnTen_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi_NCC", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string DiaChi_NCC
		{
			get
			{
				return this._DiaChi_NCC;
			}
			set
			{
				if ((this._DiaChi_NCC != value))
				{
					this.OnDiaChi_NCCChanging(value);
					this.SendPropertyChanging();
					this._DiaChi_NCC = value;
					this.SendPropertyChanged("DiaChi_NCC");
					this.OnDiaChi_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt_NCC", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Sdt_NCC
		{
			get
			{
				return this._Sdt_NCC;
			}
			set
			{
				if ((this._Sdt_NCC != value))
				{
					this.OnSdt_NCCChanging(value);
					this.SendPropertyChanging();
					this._Sdt_NCC = value;
					this.SendPropertyChanged("Sdt_NCC");
					this.OnSdt_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiThuoc_NCC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LoaiThuoc_NCC
		{
			get
			{
				return this._LoaiThuoc_NCC;
			}
			set
			{
				if ((this._LoaiThuoc_NCC != value))
				{
					this.OnLoaiThuoc_NCCChanging(value);
					this.SendPropertyChanging();
					this._LoaiThuoc_NCC = value;
					this.SendPropertyChanged("LoaiThuoc_NCC");
					this.OnLoaiThuoc_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Thuoc", Storage="_Thuocs", ThisKey="Ma_NCC", OtherKey="Ma_NCC")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
}
#pragma warning restore 1591
